### PR TITLE
Add hci_ctrl_o and remove hwpe_sel_o in cluster_control_unit

### PR DESCRIPTION
**Pull request by FrancescoConti**
Small change in the cluster control unit preliminary for the integration of HCI in the PULP cluster. The `hwpe_sel_o` signal being removed has not been used since Fulmine.

### CODE REVIEW

**Comment by FrancescoConti** [comment]
The main thing to be discussed, IMHO, is the following: since this adds a dependency (`hci`) to the `cluster_peripherals`, do we want to wait for full integration and/or benderization before merging in the master? @accuminium

**Comment by andreaskurth** [comment]
Thanks @FrancescoConti.  I think adding a `Bender.yml` and (if necessary) an `ips_list.yml` to [`hci`](https://github.com/pulp-platform/hci) before adding a dependency to `hci` to this repository would be ideal.  Is there anything that prevents us from doing this now?

**Comment by FrancescoConti** [comment]
`ips_list.yml` is already there as we used `hci` for a couple projects already. No problem in adding a `Bender.yml` either, in fact I'm working on that concurrently. Let us keep this PR in a draft stage up to when we add a `Bender.yml` there (see https://github.com/pulp-platform/hci/issues/4)

**Comment by FrancescoConti** [comment]
I did add a `Bender.yml` to `hci`. I am not 100% sure it is correct as I do not have a working setup to check it out atm, but it is pretty straightforward.

**Comment by FrancescoConti** [comment]
@accuminium is it ok for you to merge?

**Comment by andreaskurth** [comment]
Thanks for these changes, @FrancescoConti.  I just rebased this branch on `master`, so we can test it before merging.

**Comment by andreaskurth** [comment]
Since this `import`s the `hci_package`, we need to add a dependency on the `hci` repository. I just added that.

`hci` already defines a dependency on `hwpe-stream`, which is great. However, the [currently latest `1.6.x` release (`1.6.1`) of `hwpe-stream` does not have a `Bender.yml`](https://github.com/pulp-platform/hwpe-stream/tree/v1.6.1), so dependency resolution stops there. Could you tag `v1.6.2` including `Bender.yml`? Then that should work as well.

One minor thing I noted is that you are using `git@github.com:pulp-platform/...` as URL for GitHub repositories. That works as long as a user has configured GitHub SSH, but breaks when they have not. If you instead use `https://github.com/pulp-platform/...`, cloning works also for users without a GitHub SSH configuration (or even a GitHub account).

**Comment by FrancescoConti** [comment]
@accuminium both done.

**Comment by andreaskurth** [comment]
Great; with https://github.com/pulp-platform/hwpe-stream/pull/9 merged, this compiles as expected.

**Review by andreaskurth — APPROVED** [review]

**Pull request merged**
